matrix:
  include:
    - os: linux
      dist: precise
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
    - os: osx

install:
    - python setup.py install

script: python setup.py test
